name: Run Python Test Script Every 15 Mintues

on:
  schedule:
    - cron: '0,15,30,45 11-22 * * 1-5'

permissions:
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run test script
        env:
          VERKADAAPI_KEY: ${{ secrets.VERKADAAPI_KEY}}
        run: python TestScript.py

      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: test_output
          path: test_output.txt
