name: Run Python Test Script Every 15 Mintues

on:
  schedule:
    - cron: '*/15 * * * *'

permissions:
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Run test script
        run: python TestScript.py

      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: test_output
          path: test_output.txt
